name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: "Run `code --version` or check Help > About"
      placeholder: "1.85.0"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: DevStories Extension Version
      description: "Check Extensions panel or run `code --list-extensions --show-versions`"
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: "List the steps to reproduce the bug"
      placeholder: |
        1. Open a project with `.devstories/` folder
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "What did you expect to happen?"
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: "What actually happened?"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain the problem"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: "Any other context about the problem"
    validations:
      required: false
