name: Feature Request
description: Suggest an idea or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement to DevStories!

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: "What problem are you trying to solve? What's frustrating about the current behavior?"
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: "Describe the solution you'd like"
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: "Any alternative solutions or features you've considered?"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: "Any other context, mockups, or screenshots about the feature request"
    validations:
      required: false
